### ISSUE TITLE
Locations posts REST API: fix post_date and add feature image

### ISSUE THREAD

**Issue by epicfaace** [TheStanfordDaily/stanforddaily-website#100]
dates usually look like this “2019-02-06T01:10:13” but in the posts endpoint for the locations, post_date looks like “2019-02-06 01:10:13" which can’t be parsed in js

**Comment by hesyifei** [comment]
Ref: https://wordpress.stackexchange.com/questions/236249/wp-api-v2-custom-endpoint-response-formatting

**Comment by hesyifei** [comment]
Fixed. E.g., http://stanforddaily2.staging.wpengine.com/wp-json/tsd/v1/locations/1/posts
