### ISSUE TITLE
Fix article list layout

### ISSUE THREAD

**Issue by hesyifei** [TheStanfordDaily/stanforddaily-website#132]
Introduced by #129

<img width="828" alt="screen shot 2019-03-05 at 10 54 28 am" src="https://user-images.githubusercontent.com/4939421/53830297-f99b5000-3f36-11e9-9ac3-350e344fd2c6.png">

**Comment by epicfaace** [comment]
@hesyifei What screen size do you have? What page are you looking at?

Perhaps changing to `overflow: hidden` would fix this.

**Comment by hesyifei** [comment]
> @hesyifei What screen size do you have? What page are you looking at?
> 
> Perhaps changing to `overflow: hidden` would fix this.

https://www.stanforddaily.com/?s=test. `overflow: hidden;` will break your fix again.
