### ISSUE TITLE
Background of placeholder image does not match

### ISSUE THREAD

**Issue by epicfaace** [TheStanfordDaily/stanforddaily-website#193]
![image](https://user-images.githubusercontent.com/1689183/57045393-4db66e00-6c22-11e9-8977-d56716d5109f.png)

**Comment by hesyifei** [comment]
Probably should store a transparent placeholder image inside the theme folder and set the background-color. Use the logo from here: https://github.com/TheStanfordDaily/stanforddaily-graphic-assets
