### ISSUE TITLE
Hide big-news-feed label

### ISSUE THREAD

**Issue by epicfaace** [TheStanfordDaily/stanforddaily-website#27]
![image](https://user-images.githubusercontent.com/1689183/46637386-d946a100-cb10-11e8-9902-58dd1c71f090.png)

1. See what part of the code shows this label
2. Make sure this label is hidden everywhere

**Comment by hesyifei** [comment]
The label there is showing the primary category of that article (defined by the function `jnews_get_primary_category`), which is exactly `big-news-feed`. From https://www.stanforddaily.com/category/big-news-feed/, we can see that apparently `big-news-feed` category means "For the featured story in the email digest".

<img width="1123" alt="" src="https://user-images.githubusercontent.com/4939421/47408720-567b3400-d715-11e8-82b8-4624c81451ad.png">

If we want to solve this problem, we have to somehow modify the output of the function `jnews_get_primary_category` (seems like we could do that by `add_filter` to `jnews_primary_category`) to make it choose category other than `big-news-feed`.

Alternatively, we could just change `big-news-feed` to a more appealing name (like `Email-worthy Featured Story` or something like that).
