### ISSUE TITLE
Authors REST endpoint should return "profileImage" attribute

### ISSUE THREAD

**Issue by epicfaace** [TheStanfordDaily/stanforddaily-website#44]
*Problem:* We have an authors list in the mobile app, but we want to show a profile thumbnail of them as well.

*Solution:* Change this REST endpoint: https://www.stanforddaily.com/wp-json/tsd/v1/authors

Return a "profileImage" attribute for each author in the list.

**Comment by hesyifei** [comment]
Added in 7ba7e7b5a4174478fd153723c3b9492d6d19f9b2.
