### ISSUE TITLE
Subtitle migration

### ISSUE THREAD

**Issue by epicfaace** [TheStanfordDaily/stanforddaily-website#50]
Which field does jnews store the subtitle in?

**Comment by hesyifei** [comment]
JNews stores subtitles as post meta `post_subtitle`.

For example, in `jnews/class/Single/SinglePost.php`:

    public function render_subtitle()
    {
        $subtitle = wp_kses( get_post_meta( $this->post_id, 'post_subtitle', true ), wp_kses_allowed_html() );
        return apply_filters('jnews_single_subtitle', $subtitle, $this->post_id);
    }
