### ISSUE TITLE
[Authors Plugin] Alter the avatar image returned by the get_avatar() function

### ISSUE THREAD

**Issue by hesyifei** [TheStanfordDaily/stanforddaily-website#51]
By default, `get_avatar()` returns the avatar from [Gravatar](https://gravatar.com/) based on the user email.

With the TSD Authors Plugin, the user is now able to upload a profile image for themselves. As such, it would be better if `get_avatar()` could return the profile image the user uploaded.

Reference: https://codex.wordpress.org/Plugin_API/Filter_Reference/get_avatar

**Comment by epicfaace** [comment]
Nice!
