### ISSUE TITLE
Make an easier way to start development

### ISSUE THREAD

**Issue by epicfaace** [TheStanfordDaily/stanforddaily-website#58]
Using `Vagrantfile`

Coming soon...

**Comment by epicfaace** [comment]
> Another possible choice: https://github.com/Varying-Vagrant-Vagrants/VVV

Yeah, sounds like a good option. The reason why I didn't use this one is because it requires us to change our git repo structure to something that won't deploy to WPEngine.

**Comment by hesyifei** [comment]
We also need a way to test the website on mobile devices.

**Comment by epicfaace** [comment]
Can't we just use the chrome inspector for now?

![image](https://user-images.githubusercontent.com/1689183/51759347-dc907900-207c-11e9-8252-457f220c88ac.png)
