### ISSUE TITLE
No such file or directory -- wp-includes/rest-api/endpoints/class-wp-rest-autosaves-controller.php)

### ISSUE THREAD

**Issue by epicfaace** [TheStanfordDaily/stanforddaily-website#81]
**Steps to Reproduce**
- Run `vagrant up`
- Open http://localhost.stanforddaily.com in your browser.
- Get this:

### 😮  

![image](https://user-images.githubusercontent.com/1689183/51433870-ad57b300-1c09-11e9-8648-8556cee46fe8.png)

Probably has to do with the WP migration. I think it's caused by the fact that [this folder](https://github.com/TheStanfordDaily/stanforddaily-website/tree/master/wp-includes/rest-api/endpoints) doesn't have the file `class-wp-rest-autosaves-controller.php`. @hesyifei did you check in all the files created by the migration? 

I think maybe the problem is that `.gitignore` contains `wp-includes/` so it didn't check in any files from WP 5.x when you upgraded: https://github.com/TheStanfordDaily/stanforddaily-website/blob/master/.gitignore#L59

**Comment by hesyifei** [comment]
I updated the `.gitignore` based on https://github.com/github/gitignore/blob/master/WordPress.gitignore. I think it should be working fine now

**Comment by hesyifei** [comment]
I think it's working now. I've tried to re-clone the whole thing and it works.

**Comment by epicfaace** [comment]
Thanks @hesyifei !
