### ISSUE TITLE
Maybe use `wp_count_posts` here instead to speed up

### ISSUE THREAD

**Issue by epicfaace** [TheStanfordDaily/stanforddaily-website#82]
Here:
https://github.com/TheStanfordDaily/stanforddaily-website/blob/a28c8d01fd42e1958c9e0f57acbde17aebf632cb/wp-content/plugins/tsd-locations/tsd-locations.php#L85

Maybe you can use
https://developer.wordpress.org/reference/functions/wp_count_posts/

which might be faster?

**Comment by hesyifei** [comment]
`wp_count_posts` doesn't actually work. It gives something like this:
```
stdClass Object
(
    [publish] => 1714
    [future] => 0
    [draft] => 0
    [pending] => 0
    [private] => 0
    [trash] => 0
    [auto-draft] => 2
    [inherit] => 0
    [request-pending] => 0
    [request-confirmed] => 0
    [request-failed] => 0
    [request-completed] => 0
)
```

But `get_term_by` seems to be working!

**Comment by epicfaace** [comment]
What's wrong with using the `publish` attribute of the object returned by `wp_count_posts`?

**Comment by hesyifei** [comment]
```
$all_posts = get_posts( [
    tag' => implode( ",", $all_tag_slugs ),
    numberposts' => -1,
    fields' => 'ids',  // https://wordpress.stackexchange.com/a/159193/75147
] );
```

Should be good enough 🧐
