### ISSUE TITLE
Disqus comments not moving from old -> new migration

### ISSUE THREAD

**Issue by epicfaace** [TheStanfordDaily/stanforddaily-website#93]
Old site has 15 comments: https://old.stanforddaily.com/2013/03/05/why-i-support-the-call-for-stanford-university-to-divest-from-the-israeli-occupation/

![image](https://user-images.githubusercontent.com/1689183/52170965-0a269380-2709-11e9-8156-d4c40ec2fa49.png)

New site has 0 comments: 😢 https://stanforddaily.com/2013/03/05/why-i-support-the-call-for-stanford-university-to-divest-from-the-israeli-occupation/

![image](https://user-images.githubusercontent.com/1689183/52170963-02ff8580-2709-11e9-8d2f-9afcbfa4cbd5.png)

**Comment by hesyifei** [comment]
Seemed to be fixed now after we started using Disqus for WordPress plugin!
